import type { StaticImageData } from 'next/image'

import RichText from '@/components/RichText'
import { SmartLink } from '@/components/SmartLink'
import { Media } from '@/components/Media'
import { cn } from '@/utilities/ui'
import type { EnhancedMediaBlock as EnhancedMediaBlockProps } from '@/payload-types'
import React from 'react'

type CornerRadius = NonNullable<EnhancedMediaBlockProps['cornerRadius']>
type BorderStyle = NonNullable<EnhancedMediaBlockProps['borderStyle']>
type ShadowSize = NonNullable<EnhancedMediaBlockProps['shadow']>
type MaxWidth = NonNullable<EnhancedMediaBlockProps['maxWidth']>
type Alignment = NonNullable<EnhancedMediaBlockProps['alignment']>

const cornerRadiusClass = (r: CornerRadius | null | undefined): string => {
  switch (r) {
    case 'none':
      return 'rounded-none'
    case 'sm':
      return 'rounded-sm'
    case 'md':
      return 'rounded-md'
    case 'lg':
      return 'rounded-lg'
    case 'xl':
      return 'rounded-xl'
    case '2xl':
      return 'rounded-2xl'
    case 'full':
      return 'rounded-full'
    default:
      return 'rounded-lg'
  }
}

const borderClass = (b: BorderStyle | null | undefined): string => {
  switch (b) {
    case 'none':
      return ''
    case 'subtle':
      return 'border border-border/60'
    case 'default':
    default:
      return 'border border-border'
  }
}

const shadowClass = (s: ShadowSize | null | undefined): string => {
  switch (s) {
    case 'sm':
      return 'shadow-sm'
    case 'md':
      return 'shadow-md'
    case 'lg':
      return 'shadow-lg'
    case 'xl':
      return 'shadow-xl'
    case 'none':
    default:
      return ''
  }
}

const maxWidthClass = (m: MaxWidth | null | undefined): string => {
  switch (m) {
    case '7xl':
      return 'max-w-7xl'
    case '5xl':
      return 'max-w-5xl'
    case '3xl':
      return 'max-w-3xl'
    case 'full':
    default:
      return 'max-w-full'
  }
}

const alignmentClass = (a: Alignment | null | undefined): string => {
  switch (a) {
    case 'left':
      return 'mr-auto ml-0'
    case 'right':
      return 'ml-auto mr-0'
    case 'center':
    default:
      return 'mx-auto'
  }
}

/** Normalize editor input: "16:9", " 2.35 / 1 " → "2.35/1" */
const normalizeCustomAspectRatio = (input: string | null | undefined): string | null => {
  if (input == null || typeof input !== 'string') return null
  const n = input.trim().replace(/\s+/g, '').replace(':', '/')
  if (!n || !/^\d+(\.\d+)?\/\d+(\.\d+)?$/.test(n)) return null
  return n
}

const resolveEffectiveAspectRatio = (
  aspectRatio: EnhancedMediaBlockProps['aspectRatio'],
  aspectRatioCustom: EnhancedMediaBlockProps['aspectRatioCustom'],
): string | null => {
  if (!aspectRatio || aspectRatio === 'auto') return null
  if (aspectRatio === 'custom') return normalizeCustomAspectRatio(aspectRatioCustom ?? undefined)
  return aspectRatio
}

/** Inline aspect-ratio — dynamic `aspect-[…]` Tailwind classes are not generated by JIT. */
const aspectRatioStyle = (ratio: string | null | undefined): React.CSSProperties | undefined => {
  if (!ratio) return undefined
  return { aspectRatio: ratio.replace(/\//, ' / ') }
}

type Props = EnhancedMediaBlockProps & {
  captionClassName?: string
  className?: string
  enableGutter?: boolean
  imgClassName?: string
  staticImage?: StaticImageData
  disableInnerContainer?: boolean
  /** Legacy blocks saved before `widthScope` replaced `fullWidth` */
  fullWidth?: boolean | null
}

export const EnhancedMediaBlock: React.FC<Props> = (props) => {
  const {
    alignment = 'center',
    aspectRatio = 'auto',
    aspectRatioCustom,
    borderStyle = 'default',
    captionClassName,
    className,
    cornerRadius = 'lg',
    disableInnerContainer,
    enableGutter = true,
    fullWidth: legacyFullWidth,
    href,
    imgClassName,
    maxWidth = 'full',
    media,
    objectFit = 'cover',
    priority,
    shadow = 'none',
    staticImage,
    widthScope: widthScopeProp,
  } = props

  const widthScopeResolved =
    widthScopeProp ??
    (legacyFullWidth === true ? 'viewport' : 'container')
  const fullBleed = widthScopeResolved === 'viewport'

  let caption
  if (media && typeof media === 'object') caption = media.caption

  const rounded = cornerRadiusClass(cornerRadius)
  const border = borderClass(borderStyle)
  const shadowCls = shadowClass(shadow)
  const frameClasses = cn('overflow-hidden', rounded, border, shadowCls)

  const isVideo =
    typeof media === 'object' && media !== null && Boolean(media.mimeType?.includes('video'))

  const effectiveRatio = resolveEffectiveAspectRatio(aspectRatio, aspectRatioCustom)
  const aspectBoxStyle = aspectRatioStyle(effectiveRatio)
  const useAspectBox = Boolean(aspectBoxStyle)

  const objectFitCls = objectFit === 'contain' ? 'object-contain' : 'object-cover'

  const priorityLoad = priority === true

  const hrefTrimmed = typeof href === 'string' ? href.trim() : ''

  const mediaEl =
    (media || staticImage) &&
    (useAspectBox ? (
      <div className={cn('relative w-full', frameClasses)} style={aspectBoxStyle}>
        {isVideo ? (
          <Media
            className="absolute inset-0 block h-full w-full"
            priority={priorityLoad}
            resource={media}
            src={staticImage}
            videoClassName={cn('h-full w-full', objectFitCls, imgClassName)}
          />
        ) : (
          <Media
            className="absolute inset-0 block h-full w-full"
            fill
            imgClassName={cn(objectFitCls, imgClassName)}
            pictureClassName="absolute inset-0 block h-full w-full"
            priority={priorityLoad}
            resource={media}
            src={staticImage}
          />
        )}
      </div>
    ) : (
      <Media
        className={frameClasses}
        imgClassName={cn(imgClassName)}
        priority={priorityLoad}
        resource={media}
        src={staticImage}
      />
    ))

  const mediaLinked =
    mediaEl &&
    (hrefTrimmed ? (
      <SmartLink className="block cursor-pointer" href={hrefTrimmed}>
        {mediaEl}
      </SmartLink>
    ) : (
      mediaEl
    ))

  const inner = (
    <div
      className={cn(
        !fullBleed && maxWidthClass(maxWidth),
        !fullBleed && alignmentClass(alignment),
        fullBleed && 'w-full',
      )}
    >
      {mediaLinked}
    </div>
  )

  return (
    <div
      className={cn(
        {
          container: enableGutter && !fullBleed,
        },
        fullBleed && 'w-screen max-w-[100vw] relative left-1/2 -translate-x-1/2',
        className,
      )}
    >
      {inner}
      {caption && (
        <div
          className={cn(
            'mt-6',
            {
              container: !disableInnerContainer,
            },
            captionClassName,
          )}
        >
          <RichText data={caption} enableGutter={false} />
        </div>
      )}
    </div>
  )
}
