/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    'media-gifs': MediaGif;
    categories: Category;
    'listing-categories': ListingCategory;
    listings: Listing;
    users: User;
    'comment-moderation-rules': CommentModerationRule;
    comments: Comment;
    'comment-likes': CommentLike;
    livestreams: Livestream;
    'livestream-chat-messages': LivestreamChatMessage;
    'livestream-chat-event-receipts': LivestreamChatEventReceipt;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media' | 'media-gifs';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'media-gifs': MediaGifsSelect<false> | MediaGifsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'listing-categories': ListingCategoriesSelect<false> | ListingCategoriesSelect<true>;
    listings: ListingsSelect<false> | ListingsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'comment-moderation-rules': CommentModerationRulesSelect<false> | CommentModerationRulesSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    'comment-likes': CommentLikesSelect<false> | CommentLikesSelect<true>;
    livestreams: LivestreamsSelect<false> | LivestreamsSelect<true>;
    'livestream-chat-messages': LivestreamChatMessagesSelect<false> | LivestreamChatMessagesSelect<true>;
    'livestream-chat-event-receipts': LivestreamChatEventReceiptsSelect<false> | LivestreamChatEventReceiptsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'general-settings': GeneralSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'general-settings': GeneralSettingsSelect<false> | GeneralSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'categories';
                  value: number | Category;
                } | null)
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | AIEcosystemMapBlock
    | ContentBlock
    | MediaBlock
    | EnhancedMediaBlock
    | ArchiveBlock
    | FormBlock
    | FeaturedPostsSideMediaBlock
    | HeroCarouselBlock
    | PortalSplitLayoutBlock
    | HumanitiesCornerBlock
    | MediaHubTriptychBlock
    | NewsletterSignupBlock
    | YouTubeEmbedBlock
    | ListingsCategoriesGridBlock
    | ListingsCategoryItemBlock
    | MarketplaceStatsBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  /**
   * Ảnh cuối trang chi tiết. Để trống sẽ dùng ảnh mặc định trong General Settings → Default post page images (nếu có).
   */
  footerImage?: (number | null) | Media;
  /**
   * Link khi nhấn ảnh cuối trang (tùy chọn). Nếu không set mà dùng ảnh mặc định global, link lấy từ global.
   */
  footerImageHref?: string | null;
  /**
   * Ảnh quảng cáo sidebar. Để trống sẽ dùng ảnh mặc định trong General Settings (nếu có).
   */
  sidebarAdImage?: (number | null) | Media;
  /**
   * Link quảng cáo sidebar (tùy chọn). Nếu không set mà dùng ảnh mặc định global, link lấy từ global.
   */
  sidebarAdHref?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * Số lượt xem bài viết
   */
  views?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
      | {
          relationTo?: 'media-gifs';
          value: number | MediaGif;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: ('media' | 'media-gifs')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-gifs".
 */
export interface MediaGif {
  id: number;
  alt?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles: ('admin' | 'member')[];
  /**
   * Google account subject (sub). Set automatically for OAuth sign-in.
   */
  googleSub?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'categories';
                value: number | Category;
              } | null)
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AIEcosystemMapBlock".
 */
export interface AIEcosystemMapBlock {
  heading: string;
  centerImage: number | Media;
  /**
   * Optional link for the center image.
   */
  centerImageHref?: string | null;
  centerTopLeftLabel: string;
  centerTopMiddleLabel: string;
  centerTopRightLabel: string;
  centerMiddleLeftLabel: string;
  centerMiddleRightLabel: string;
  centerRightUpperLabel: string;
  centerBottomLeftLabel: string;
  centerBottomMiddleLabel: string;
  centerBottomRightLabel: string;
  centerBottomFarLeftLabel: string;
  centerBottomFarRightLabel: string;
  forumCard: {
    title: string;
    image: number | Media;
    /**
     * Internal path (e.g. /posts/my-slug) or full URL.
     */
    href?: string | null;
  };
  studyGroupCard: {
    title: string;
    image: number | Media;
    /**
     * Internal path (e.g. /posts/my-slug) or full URL.
     */
    href?: string | null;
  };
  policyCard: {
    title: string;
    image: number | Media;
    /**
     * Internal path (e.g. /posts/my-slug) or full URL.
     */
    href?: string | null;
  };
  openSourceCard: {
    title: string;
    image: number | Media;
    /**
     * Internal path (e.g. /posts/my-slug) or full URL.
     */
    href?: string | null;
  };
  datasetCard: {
    title: string;
    image: number | Media;
    /**
     * Internal path (e.g. /posts/my-slug) or full URL.
     */
    href?: string | null;
  };
  libraryCard: {
    title: string;
    image: number | Media;
    /**
     * Internal path (e.g. /posts/my-slug) or full URL.
     */
    href?: string | null;
  };
  toolsCard: {
    title: string;
    image: number | Media;
    /**
     * Internal path (e.g. /posts/my-slug) or full URL.
     */
    href?: string | null;
  };
  allianceCard: {
    title: string;
    image: number | Media;
    /**
     * Internal path (e.g. /posts/my-slug) or full URL.
     */
    href?: string | null;
  };
  mindsetCard: {
    title: string;
    image: number | Media;
    /**
     * Internal path (e.g. /posts/my-slug) or full URL.
     */
    href?: string | null;
  };
  jobsCard: {
    title: string;
    image: number | Media;
    /**
     * Internal path (e.g. /posts/my-slug) or full URL.
     */
    href?: string | null;
  };
  reportsCard: {
    title: string;
    image: number | Media;
    /**
     * Internal path (e.g. /posts/my-slug) or full URL.
     */
    href?: string | null;
  };
  eventsCard: {
    title: string;
    image: number | Media;
    /**
     * Internal path (e.g. /posts/my-slug) or full URL.
     */
    href?: string | null;
  };
  startupCard: {
    title: string;
    image: number | Media;
    /**
     * Internal path (e.g. /posts/my-slug) or full URL.
     */
    href?: string | null;
  };
  cooperationCard: {
    title: string;
    image: number | Media;
    /**
     * Internal path (e.g. /posts/my-slug) or full URL.
     */
    href?: string | null;
  };
  communityProjectsCard: {
    title: string;
    image: number | Media;
    /**
     * Internal path (e.g. /posts/my-slug) or full URL.
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'aiEcosystemMap';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'categories';
                value: number | Category;
              } | null)
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EnhancedMediaBlock".
 */
export interface EnhancedMediaBlock {
  media: number | Media;
  /**
   * If set, the image/video becomes clickable. Internal paths (e.g. /posts/slug) or https://, mailto:, tel:.
   */
  href?: string | null;
  /**
   * Container: media stays inside the site content width. Viewport: breaks out to full browser width.
   */
  widthScope?: ('container' | 'viewport') | null;
  priority?: boolean | null;
  maxWidth?: ('full' | '7xl' | '5xl' | '3xl') | null;
  alignment?: ('left' | 'center' | 'right') | null;
  aspectRatio?: ('auto' | '1/1' | '4/3' | '3/2' | '16/9' | '21/9' | '2/3' | '9/16' | 'custom') | null;
  /**
   * Width and height separated by / or : (examples: 16/9, 2.35:1, 1.85/1).
   */
  aspectRatioCustom?: string | null;
  objectFit?: ('cover' | 'contain') | null;
  cornerRadius?: ('none' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | 'full') | null;
  borderStyle?: ('none' | 'subtle' | 'default') | null;
  shadow?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'enhancedMediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedPostsSideMediaBlock".
 */
export interface FeaturedPostsSideMediaBlock {
  /**
   * Choose data source for posts.
   */
  source: 'manual' | 'latest';
  /**
   * Main post
   */
  mainPost?: (number | null) | Post;
  /**
   * Exactly 2 small posts (first row under the main post).
   */
  subPosts?: (number | Post)[] | null;
  /**
   * Third column: full-height image (replaces the former 3rd small post). Optional.
   */
  smallRowPromoImage?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'media-gifs';
        value: number | MediaGif;
      } | null);
  /**
   * Optional link when the promo image is clicked (e.g. /posts/slug or https://…).
   */
  smallRowPromoHref?: string | null;
  /**
   * Image/GIF displayed on the right side.
   */
  sideMedia:
    | {
        relationTo: 'media';
        value: number | Media;
      }
    | {
        relationTo: 'media-gifs';
        value: number | MediaGif;
      };
  /**
   * Optional link when the side image is clicked (e.g. /posts/slug or https://…).
   */
  sideMediaHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredPostsSideMedia';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroCarouselBlock".
 */
export interface HeroCarouselBlock {
  /**
   * Autoplay delay in milliseconds. Set 0 to disable autoplay.
   */
  autoplayDelay?: number | null;
  slides: {
    type: 'image' | 'ctaHero';
    media: number | Media;
    /**
     * Optional link for image slides.
     */
    href?: string | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'categories';
                  value: number | Category;
                } | null)
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroCarousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortalSplitLayoutBlock".
 */
export interface PortalSplitLayoutBlock {
  /**
   * Left column: vertical post feed.
   */
  leftSource: 'manual' | 'latest';
  /**
   * Posts for the left column (order is preserved).
   */
  leftPosts?: (number | Post)[] | null;
  leftLatestLimit?: number | null;
  /**
   * Filter latest posts by categories (multi-select).
   */
  leftCategoryFilters?: (number | Category)[] | null;
  /**
   * 1-based start position after sorting by newest published date.
   */
  leftLatestFrom?: number | null;
  /**
   * Inclusive end position. Example: from 9 to 16 skips the first 8 newest posts.
   */
  leftLatestTo?: number | null;
  row1LeftTitle?: string | null;
  row1LeftAccent?: ('gold' | 'yellow' | 'green' | 'purple' | 'blue' | 'red' | 'teal') | null;
  row1LeftAccentCustomHex?: string | null;
  /**
   * Central graphic (ecosystem diagram).
   */
  row1CenterGraphic?: (number | null) | Media;
  row1TagItems?:
    | {
        label: string;
        /**
         * Optional URL
         */
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Smallest radius as % of the box’s shorter side (tags closer to center). Pair with max below (default 16–52).
   */
  row1OrbitRadiusMinPct?: number | null;
  /**
   * Largest radius before angle squeezing (tags farther out). Must be greater than min.
   */
  row1OrbitRadiusMaxPct?: number | null;
  row1GridItems?:
    | {
        /**
         * Optional small icon
         */
        icon?: (number | null) | Media;
        label: string;
        /**
         * Optional URL (leave empty for text-only cell).
         */
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  row1RightTitle?: string | null;
  row1RightAccent?: ('gold' | 'yellow' | 'green' | 'purple' | 'blue' | 'red' | 'teal') | null;
  row1RightAccentCustomHex?: string | null;
  row1RightCards?:
    | {
        image: number | Media;
        caption: string;
        /**
         * Optional URL (leave empty for non-clickable card).
         */
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  standardSections?:
    | {
        sectionTitle: string;
        accent: 'gold' | 'yellow' | 'green' | 'purple' | 'blue' | 'red' | 'teal';
        /**
         * Optional HEX override for accent (e.g. #005C5C). Keeps preset when empty.
         */
        accentCustomHex?: string | null;
        featuredPost: number | Post;
        /**
         * Exactly 3 smaller posts
         */
        subPosts?: (number | Post)[] | null;
        /**
         * Exactly 6 posts for the 2×3 title grid
         */
        footerPosts?: (number | Post)[] | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'portalSplitLayout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HumanitiesCornerBlock".
 */
export interface HumanitiesCornerBlock {
  /**
   * Image for the left column (vertical banner).
   */
  bannerImage: number | Media;
  /**
   * Optional heading above the list (centered), e.g. section name.
   */
  listTitle?: string | null;
  items?:
    | {
        itemType?: ('post' | 'manual') | null;
        /**
         * Title and URL are taken from the post.
         */
        post?: (number | null) | Post;
        title?: string | null;
        /**
         * Internal path (e.g. /posts/my-slug) or full URL.
         */
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'humanitiesCorner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaHubTriptychBlock".
 */
export interface MediaHubTriptychBlock {
  podcastColumn?: {
    sectionTitle?: string | null;
    items?:
      | {
          title: string;
          meta?: string | null;
          thumbnail: number | Media;
          /**
           * Internal path or https://
           */
          link?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  videoColumn: {
    sectionTitle?: string | null;
    featured: {
      source: 'embed' | 'media';
      /**
       * https only. Supports YouTube/Vimeo watch links or a direct video file URL.
       */
      embedUrl?: string | null;
      /**
       * Uploaded video (MP4, WebM, etc.). Renders with native controls.
       */
      videoMedia?: (number | null) | Media;
      /**
       * Optional preview or poster image (e.g. before play, or when only thumbnail is set).
       */
      thumbnail?: (number | null) | Media;
      caption?: string | null;
    };
    gridItems?:
      | {
          source: 'embed' | 'media';
          /**
           * https only. Supports YouTube/Vimeo watch links or a direct video file URL.
           */
          embedUrl?: string | null;
          /**
           * Uploaded video (MP4, WebM, etc.). Renders with native controls.
           */
          videoMedia?: (number | null) | Media;
          /**
           * Optional preview / poster for native or uploaded video; or static preview when no URL/file.
           */
          thumbnail?: (number | null) | Media;
          title: string;
          /**
           * Wraps title in a link when set.
           */
          link?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  photoColumn: {
    sectionTitle?: string | null;
    featured: {
      image: number | Media;
      title: string;
      /**
       * e.g. Thứ 6, 25/05/2025 | 23:43
       */
      dateLine?: string | null;
    };
    bottomItems?:
      | {
          image: number | Media;
          title: string;
          link?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaHubTriptych';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterSignupBlock".
 */
export interface NewsletterSignupBlock {
  /**
   * Tạo form trong Forms với ít nhất một trường Email. Gửi bài sẽ lưu vào Form Submissions (đọc qua MCP Payload: findFormSubmissions).
   */
  form: number | Form;
  eyebrow?: string | null;
  headline?: string | null;
  description?: string | null;
  emailPlaceholder?: string | null;
  submitLabel?: string | null;
  disclaimer?: string | null;
  /**
   * URL cho từ “điều khoản” (vd. /terms hoặc https://...).
   */
  termsUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsletterSignup';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "YouTubeEmbedBlock".
 */
export interface YouTubeEmbedBlock {
  title?: string | null;
  videoTitle: string;
  youtubeUrl: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'youtubeEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ListingsCategoriesGridBlock".
 */
export interface ListingsCategoriesGridBlock {
  title?: string | null;
  source: 'all' | 'manual';
  categories?: (number | ListingCategory)[] | null;
  /**
   * Only used when source is "All categories".
   */
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'listingsCategoriesGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-categories".
 */
export interface ListingCategory {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Ảnh thumbnail đại diện cho danh mục listings.
   */
  thumbnail?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ListingsCategoryItemBlock".
 */
export interface ListingsCategoryItemBlock {
  category: number | ListingCategory;
  /**
   * Optional custom title. Leave empty to use category title.
   */
  title?: string | null;
  limit?: number | null;
  viewMoreLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'listingsCategoryItem';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MarketplaceStatsBlock".
 */
export interface MarketplaceStatsBlock {
  title: string;
  subtitle?: string | null;
  items?:
    | {
        icon: 'users' | 'sale' | 'rent';
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  buttonLabel?: string | null;
  buttonUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'marketplaceStats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Chọn một hoặc nhiều danh mục cho tin đăng này.
   */
  categories?: (number | ListingCategory)[] | null;
  listingType: 'job-seeking' | 'job-offer' | 'service' | 'other';
  /**
   * Ví dụ: Thỏa thuận, 15 triệu/tháng, 500.000 VNĐ/buổi.
   */
  priceLabel: string;
  /**
   * Mô tả ngắn hiển thị ở phần mở đầu.
   */
  summary?: string | null;
  /**
   * Nội dung mô tả chính của tin đăng.
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  contactPhone: string;
  city: string;
  district?: string | null;
  address?: string | null;
  packageName?: string | null;
  contactName: string;
  supportPhone?: string | null;
  statusLabel?: ('available' | 'hidden' | 'closed') | null;
  zaloUrl?: string | null;
  avatar?: (number | null) | Media;
  /**
   * Ảnh đại diện của tin khi hiển thị trong danh sách cập nhật.
   */
  thumbnail?: (number | null) | Media;
  /**
   * Bộ sưu tập ảnh của tin đăng.
   */
  gallery?: (number | Media)[] | null;
  createdBy: number | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Từ khóa cấm hoặc user bị chặn bình luận.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comment-moderation-rules".
 */
export interface CommentModerationRule {
  id: number;
  ruleType: 'blockedKeyword' | 'blockedUser';
  /**
   * Mỗi dòng một cụm từ cấm. So khớp chuỗi con sau khi chuẩn hóa chữ thường (Enter = tách cụm).
   */
  keyword?: string | null;
  blockedUser?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  post: number | Post;
  author: number | User;
  /**
   * Cho phep tra loi 1 cap (comment -> reply).
   */
  parentComment?: (number | null) | Comment;
  body: string;
  /**
   * Cập nhật tự động khi thành viên thích bình luận.
   */
  likeCount?: number | null;
  /**
   * Thành viên: tự động approved nếu qua blacklist, rejected nếu khớp từ khóa cấm. Pending chỉ dùng khi admin đặt tay.
   */
  status: 'pending' | 'approved' | 'rejected';
  /**
   * Điền tự động khi nội dung khớp blacklist.
   */
  rejectionReason?: 'blocked_keyword' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comment-likes".
 */
export interface CommentLike {
  id: number;
  comment: number | Comment;
  user: number | User;
  reaction: 'like' | 'love' | 'haha' | 'wow' | 'sad' | 'angry';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "livestreams".
 */
export interface Livestream {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  status: 'draft' | 'scheduled' | 'live' | 'ended';
  callId: string;
  callType: string;
  chatChannelCid?: string | null;
  description?: string | null;
  scheduledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "livestream-chat-messages".
 */
export interface LivestreamChatMessage {
  id: number;
  streamMessageId: string;
  channelCid: string;
  channelType: string;
  channelId: string;
  livestream?: (number | null) | Livestream;
  authorStreamUserId: string;
  authorName?: string | null;
  text?: string | null;
  reactionLikeCount?: number | null;
  createdAtStream: string;
  updatedAtStream: string;
  deletedAt?: string | null;
  rawPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "livestream-chat-event-receipts".
 */
export interface LivestreamChatEventReceipt {
  id: number;
  eventId: string;
  eventType: string;
  channelCid?: string | null;
  processedAt: string;
  rawPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  posts?: {
    /**
     * Allow clients to find posts.
     */
    find?: boolean | null;
    /**
     * Allow clients to update posts.
     */
    update?: boolean | null;
  };
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
  };
  categories?: {
    /**
     * Allow clients to find categories.
     */
    find?: boolean | null;
  };
  forms?: {
    /**
     * Allow clients to find forms.
     */
    find?: boolean | null;
    /**
     * Allow clients to create forms.
     */
    create?: boolean | null;
    /**
     * Allow clients to update forms.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete forms.
     */
    delete?: boolean | null;
  };
  formSubmissions?: {
    /**
     * Allow clients to find form-submissions.
     */
    find?: boolean | null;
    /**
     * Allow clients to create form-submissions.
     */
    create?: boolean | null;
  };
  listings?: {
    /**
     * Allow clients to find listings.
     */
    find?: boolean | null;
    /**
     * Allow clients to create listings.
     */
    create?: boolean | null;
    /**
     * Allow clients to update listings.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete listings.
     */
    delete?: boolean | null;
  };
  header?: {
    /**
     * Allow clients to find header global.
     */
    find?: boolean | null;
  };
  footer?: {
    /**
     * Allow clients to find footer global.
     */
    find?: boolean | null;
  };
  generalSettings?: {
    /**
     * Allow clients to find general-settings global.
     */
    find?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'media-gifs';
        value: number | MediaGif;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'listing-categories';
        value: number | ListingCategory;
      } | null)
    | ({
        relationTo: 'listings';
        value: number | Listing;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'comment-moderation-rules';
        value: number | CommentModerationRule;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'comment-likes';
        value: number | CommentLike;
      } | null)
    | ({
        relationTo: 'livestreams';
        value: number | Livestream;
      } | null)
    | ({
        relationTo: 'livestream-chat-messages';
        value: number | LivestreamChatMessage;
      } | null)
    | ({
        relationTo: 'livestream-chat-event-receipts';
        value: number | LivestreamChatEventReceipt;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        aiEcosystemMap?: T | AIEcosystemMapBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        enhancedMediaBlock?: T | EnhancedMediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        featuredPostsSideMedia?: T | FeaturedPostsSideMediaBlockSelect<T>;
        heroCarousel?: T | HeroCarouselBlockSelect<T>;
        portalSplitLayout?: T | PortalSplitLayoutBlockSelect<T>;
        humanitiesCorner?: T | HumanitiesCornerBlockSelect<T>;
        mediaHubTriptych?: T | MediaHubTriptychBlockSelect<T>;
        newsletterSignup?: T | NewsletterSignupBlockSelect<T>;
        youtubeEmbed?: T | YouTubeEmbedBlockSelect<T>;
        listingsCategoriesGrid?: T | ListingsCategoriesGridBlockSelect<T>;
        listingsCategoryItem?: T | ListingsCategoryItemBlockSelect<T>;
        marketplaceStats?: T | MarketplaceStatsBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AIEcosystemMapBlock_select".
 */
export interface AIEcosystemMapBlockSelect<T extends boolean = true> {
  heading?: T;
  centerImage?: T;
  centerImageHref?: T;
  centerTopLeftLabel?: T;
  centerTopMiddleLabel?: T;
  centerTopRightLabel?: T;
  centerMiddleLeftLabel?: T;
  centerMiddleRightLabel?: T;
  centerRightUpperLabel?: T;
  centerBottomLeftLabel?: T;
  centerBottomMiddleLabel?: T;
  centerBottomRightLabel?: T;
  centerBottomFarLeftLabel?: T;
  centerBottomFarRightLabel?: T;
  forumCard?:
    | T
    | {
        title?: T;
        image?: T;
        href?: T;
      };
  studyGroupCard?:
    | T
    | {
        title?: T;
        image?: T;
        href?: T;
      };
  policyCard?:
    | T
    | {
        title?: T;
        image?: T;
        href?: T;
      };
  openSourceCard?:
    | T
    | {
        title?: T;
        image?: T;
        href?: T;
      };
  datasetCard?:
    | T
    | {
        title?: T;
        image?: T;
        href?: T;
      };
  libraryCard?:
    | T
    | {
        title?: T;
        image?: T;
        href?: T;
      };
  toolsCard?:
    | T
    | {
        title?: T;
        image?: T;
        href?: T;
      };
  allianceCard?:
    | T
    | {
        title?: T;
        image?: T;
        href?: T;
      };
  mindsetCard?:
    | T
    | {
        title?: T;
        image?: T;
        href?: T;
      };
  jobsCard?:
    | T
    | {
        title?: T;
        image?: T;
        href?: T;
      };
  reportsCard?:
    | T
    | {
        title?: T;
        image?: T;
        href?: T;
      };
  eventsCard?:
    | T
    | {
        title?: T;
        image?: T;
        href?: T;
      };
  startupCard?:
    | T
    | {
        title?: T;
        image?: T;
        href?: T;
      };
  cooperationCard?:
    | T
    | {
        title?: T;
        image?: T;
        href?: T;
      };
  communityProjectsCard?:
    | T
    | {
        title?: T;
        image?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EnhancedMediaBlock_select".
 */
export interface EnhancedMediaBlockSelect<T extends boolean = true> {
  media?: T;
  href?: T;
  widthScope?: T;
  priority?: T;
  maxWidth?: T;
  alignment?: T;
  aspectRatio?: T;
  aspectRatioCustom?: T;
  objectFit?: T;
  cornerRadius?: T;
  borderStyle?: T;
  shadow?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedPostsSideMediaBlock_select".
 */
export interface FeaturedPostsSideMediaBlockSelect<T extends boolean = true> {
  source?: T;
  mainPost?: T;
  subPosts?: T;
  smallRowPromoImage?: T;
  smallRowPromoHref?: T;
  sideMedia?: T;
  sideMediaHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroCarouselBlock_select".
 */
export interface HeroCarouselBlockSelect<T extends boolean = true> {
  autoplayDelay?: T;
  slides?:
    | T
    | {
        type?: T;
        media?: T;
        href?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortalSplitLayoutBlock_select".
 */
export interface PortalSplitLayoutBlockSelect<T extends boolean = true> {
  leftSource?: T;
  leftPosts?: T;
  leftLatestLimit?: T;
  leftCategoryFilters?: T;
  leftLatestFrom?: T;
  leftLatestTo?: T;
  row1LeftTitle?: T;
  row1LeftAccent?: T;
  row1LeftAccentCustomHex?: T;
  row1CenterGraphic?: T;
  row1TagItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  row1OrbitRadiusMinPct?: T;
  row1OrbitRadiusMaxPct?: T;
  row1GridItems?:
    | T
    | {
        icon?: T;
        label?: T;
        href?: T;
        id?: T;
      };
  row1RightTitle?: T;
  row1RightAccent?: T;
  row1RightAccentCustomHex?: T;
  row1RightCards?:
    | T
    | {
        image?: T;
        caption?: T;
        href?: T;
        id?: T;
      };
  standardSections?:
    | T
    | {
        sectionTitle?: T;
        accent?: T;
        accentCustomHex?: T;
        featuredPost?: T;
        subPosts?: T;
        footerPosts?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HumanitiesCornerBlock_select".
 */
export interface HumanitiesCornerBlockSelect<T extends boolean = true> {
  bannerImage?: T;
  listTitle?: T;
  items?:
    | T
    | {
        itemType?: T;
        post?: T;
        title?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaHubTriptychBlock_select".
 */
export interface MediaHubTriptychBlockSelect<T extends boolean = true> {
  podcastColumn?:
    | T
    | {
        sectionTitle?: T;
        items?:
          | T
          | {
              title?: T;
              meta?: T;
              thumbnail?: T;
              link?: T;
              id?: T;
            };
      };
  videoColumn?:
    | T
    | {
        sectionTitle?: T;
        featured?:
          | T
          | {
              source?: T;
              embedUrl?: T;
              videoMedia?: T;
              thumbnail?: T;
              caption?: T;
            };
        gridItems?:
          | T
          | {
              source?: T;
              embedUrl?: T;
              videoMedia?: T;
              thumbnail?: T;
              title?: T;
              link?: T;
              id?: T;
            };
      };
  photoColumn?:
    | T
    | {
        sectionTitle?: T;
        featured?:
          | T
          | {
              image?: T;
              title?: T;
              dateLine?: T;
            };
        bottomItems?:
          | T
          | {
              image?: T;
              title?: T;
              link?: T;
              id?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterSignupBlock_select".
 */
export interface NewsletterSignupBlockSelect<T extends boolean = true> {
  form?: T;
  eyebrow?: T;
  headline?: T;
  description?: T;
  emailPlaceholder?: T;
  submitLabel?: T;
  disclaimer?: T;
  termsUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "YouTubeEmbedBlock_select".
 */
export interface YouTubeEmbedBlockSelect<T extends boolean = true> {
  title?: T;
  videoTitle?: T;
  youtubeUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ListingsCategoriesGridBlock_select".
 */
export interface ListingsCategoriesGridBlockSelect<T extends boolean = true> {
  title?: T;
  source?: T;
  categories?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ListingsCategoryItemBlock_select".
 */
export interface ListingsCategoryItemBlockSelect<T extends boolean = true> {
  category?: T;
  title?: T;
  limit?: T;
  viewMoreLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MarketplaceStatsBlock_select".
 */
export interface MarketplaceStatsBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  items?:
    | T
    | {
        icon?: T;
        value?: T;
        label?: T;
        id?: T;
      };
  buttonLabel?: T;
  buttonUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  footerImage?: T;
  footerImageHref?: T;
  sidebarAdImage?: T;
  sidebarAdHref?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  views?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-gifs_select".
 */
export interface MediaGifsSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-categories_select".
 */
export interface ListingCategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  thumbnail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  categories?: T;
  listingType?: T;
  priceLabel?: T;
  summary?: T;
  description?: T;
  contactPhone?: T;
  city?: T;
  district?: T;
  address?: T;
  packageName?: T;
  contactName?: T;
  supportPhone?: T;
  statusLabel?: T;
  zaloUrl?: T;
  avatar?: T;
  thumbnail?: T;
  gallery?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  googleSub?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comment-moderation-rules_select".
 */
export interface CommentModerationRulesSelect<T extends boolean = true> {
  ruleType?: T;
  keyword?: T;
  blockedUser?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  post?: T;
  author?: T;
  parentComment?: T;
  body?: T;
  likeCount?: T;
  status?: T;
  rejectionReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comment-likes_select".
 */
export interface CommentLikesSelect<T extends boolean = true> {
  comment?: T;
  user?: T;
  reaction?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "livestreams_select".
 */
export interface LivestreamsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  status?: T;
  callId?: T;
  callType?: T;
  chatChannelCid?: T;
  description?: T;
  scheduledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "livestream-chat-messages_select".
 */
export interface LivestreamChatMessagesSelect<T extends boolean = true> {
  streamMessageId?: T;
  channelCid?: T;
  channelType?: T;
  channelId?: T;
  livestream?: T;
  authorStreamUserId?: T;
  authorName?: T;
  text?: T;
  reactionLikeCount?: T;
  createdAtStream?: T;
  updatedAtStream?: T;
  deletedAt?: T;
  rawPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "livestream-chat-event-receipts_select".
 */
export interface LivestreamChatEventReceiptsSelect<T extends boolean = true> {
  eventId?: T;
  eventType?: T;
  channelCid?: T;
  processedAt?: T;
  rawPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  posts?:
    | T
    | {
        find?: T;
        update?: T;
      };
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  media?:
    | T
    | {
        find?: T;
      };
  categories?:
    | T
    | {
        find?: T;
      };
  forms?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  formSubmissions?:
    | T
    | {
        find?: T;
        create?: T;
      };
  listings?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  header?:
    | T
    | {
        find?: T;
      };
  footer?:
    | T
    | {
        find?: T;
      };
  generalSettings?:
    | T
    | {
        find?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  bannerImage?: (number | null) | Media;
  /**
   * Optional URL when users click the banner image.
   */
  bannerLink?: string | null;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'categories';
                value: number | Category;
              } | null)
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  categoriesHeading?: string | null;
  categoryColumns?:
    | {
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'categories';
                      value: number | Category;
                    } | null)
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  downloadsTitle?: string | null;
  appStoreUrl?: string | null;
  googlePlayUrl?: string | null;
  appStoreBadge?: (number | null) | Media;
  googlePlayBadge?: (number | null) | Media;
  hotlineTitle?: string | null;
  hotlines?:
    | {
        label: string;
        phone: string;
        /**
         * Example: tel:+84938381100
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  contactLinksHeading?: string | null;
  contactLinks?:
    | {
        icon: 'mail' | 'advertising' | 'terms' | 'privacy' | 'cookies';
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'categories';
                value: number | Category;
              } | null)
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  featureImage?: (number | null) | Media;
  brandTitle?: string | null;
  brandTagline?: string | null;
  contentResponsibility?: string | null;
  headquartersLabel?: string | null;
  headquartersAddress?: string | null;
  phoneLabel?: string | null;
  centerPhone?: string | null;
  /**
   * tel:… — optional if empty, uses center phone
   */
  centerPhoneHref?: string | null;
  emailLabel?: string | null;
  centerEmail?: string | null;
  socialHeading?: string | null;
  socialFacebook?: string | null;
  socialX?: string | null;
  socialYoutube?: string | null;
  socialTiktok?: string | null;
  socialRss?: string | null;
  promoTitle?: string | null;
  promoSubtitle?: string | null;
  promoHref?: string | null;
  licenseLine?: string | null;
  copyrightLine?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure general site information such as site name, logo, contact details and social links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings".
 */
export interface GeneralSetting {
  id: number;
  siteName?: string | null;
  siteDescription?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  /**
   * Add your social media profile URLs.
   */
  socialLinks?: {
    facebook?: string | null;
    twitter?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
  };
  footerContent?: {
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    copyright?: string | null;
  };
  /**
   * Fallback when a post leaves footer or sidebar ad images empty. Per-post values always win.
   */
  postPageAssets?: {
    /**
     * Shown at the bottom of the post when the post has no footer image.
     */
    footerImage?: (number | null) | Media;
    /**
     * Optional click target for the default footer image.
     */
    footerImageHref?: string | null;
    /**
     * Shown in the sidebar when the post has no sidebar ad image.
     */
    sidebarAdImage?: (number | null) | Media;
    /**
     * Optional click target for the default sidebar ad.
     */
    sidebarAdHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  bannerImage?: T;
  bannerLink?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  categoriesHeading?: T;
  categoryColumns?:
    | T
    | {
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  downloadsTitle?: T;
  appStoreUrl?: T;
  googlePlayUrl?: T;
  appStoreBadge?: T;
  googlePlayBadge?: T;
  hotlineTitle?: T;
  hotlines?:
    | T
    | {
        label?: T;
        phone?: T;
        href?: T;
        id?: T;
      };
  contactLinksHeading?: T;
  contactLinks?:
    | T
    | {
        icon?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  featureImage?: T;
  brandTitle?: T;
  brandTagline?: T;
  contentResponsibility?: T;
  headquartersLabel?: T;
  headquartersAddress?: T;
  phoneLabel?: T;
  centerPhone?: T;
  centerPhoneHref?: T;
  emailLabel?: T;
  centerEmail?: T;
  socialHeading?: T;
  socialFacebook?: T;
  socialX?: T;
  socialYoutube?: T;
  socialTiktok?: T;
  socialRss?: T;
  promoTitle?: T;
  promoSubtitle?: T;
  promoHref?: T;
  licenseLine?: T;
  copyrightLine?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings_select".
 */
export interface GeneralSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  logo?: T;
  favicon?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  socialLinks?:
    | T
    | {
        facebook?: T;
        twitter?: T;
        instagram?: T;
        linkedin?: T;
        youtube?: T;
      };
  footerContent?:
    | T
    | {
        content?: T;
        copyright?: T;
      };
  postPageAssets?:
    | T
    | {
        footerImage?: T;
        footerImageHref?: T;
        sidebarAdImage?: T;
        sidebarAdHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}